[await_promise.py]
  [test_await_resolve_date]
    expected: FAIL

  [test_await_resolve_map]
    expected: FAIL

  [test_await_resolve_primitive[Infinity-+Infinity-number\]]
    expected: FAIL

  [test_await_resolve_primitive[42n-42-bigint\]]
    expected: FAIL

  [test_await_resolve_set]
    expected: FAIL
