[exception_details.py]
  [test_exception_details[([1, 2\][Symbol.iterator\]())-expected28-True\]]
    expected: FAIL

  [test_exception_details[([1, 2\][Symbol.iterator\]())-expected28-False\]]
    expected: FAIL
