[exception_details.py]
  [test_exception_details[new RegExp(/foo/g)-expected20-False\]]
    expected: ERROR

  [test_exception_details[new Date(1654004849000)-expected21-True\]]
    expected: ERROR

  [test_exception_details[new Date(1654004849000)-expected21-False\]]
    expected: ERROR

  [test_exception_details[new Map([[1, 2\], ['foo', 'bar'\], [true, false\], ['baz', [1\]\]\])-expected22-True\]]
    expected: ERROR

  [test_exception_details[new Map([[1, 2\], ['foo', 'bar'\], [true, false\], ['baz', [1\]\]\])-expected22-False\]]
    expected: ERROR

  [test_exception_details[new Set([1, 'foo', true, [1\], new Map([[1,2\]\])\])-expected23-True\]]
    expected: ERROR

  [test_exception_details[new Set([1, 'foo', true, [1\], new Map([[1,2\]\])\])-expected23-False\]]
    expected: ERROR

  [test_exception_details[new WeakMap()-expected24-True\]]
    expected: ERROR

  [test_exception_details[new WeakMap()-expected24-False\]]
    expected: ERROR

  [test_exception_details[new WeakSet()-expected25-True\]]
    expected: ERROR

  [test_exception_details[new WeakSet()-expected25-False\]]
    expected: ERROR

  [test_exception_details[new Error('SOME_ERROR_TEXT')-expected26-True\]]
    expected: ERROR

  [test_exception_details[new Error('SOME_ERROR_TEXT')-expected26-False\]]
    expected: ERROR

  [test_exception_details[Promise.resolve()-expected27-True\]]
    expected: ERROR

  [test_exception_details[Promise.resolve()-expected27-False\]]
    expected: ERROR

  [test_exception_details[new Int32Array()-expected28-True\]]
    expected: ERROR

  [test_exception_details[new Int32Array()-expected28-False\]]
    expected: ERROR

  [test_exception_details[new ArrayBuffer()-expected29-True\]]
    expected: ERROR

  [test_exception_details[new ArrayBuffer()-expected29-False\]]
    expected: ERROR

  [test_exception_details[document.createElement('div')-expected30-True\]]
    expected: ERROR

  [test_exception_details[document.createElement('div')-expected30-False\]]
    expected: ERROR

  [test_exception_details[window-expected31-True\]]
    expected: ERROR

  [test_exception_details[window-expected31-False\]]
    expected: ERROR

  [test_rejected_promise[True\]]
    expected: ERROR

  [test_rejected_promise[False\]]
    expected: ERROR
