[connect.py]
  expected: ERROR
  [test_bidi_session_with_different_capability[capabilities0\]]
    expected: ERROR
