[stacktrace.py]
  expected: ERROR
  [test_console_entry_sync_callstack[assert-True\]]
    expected: FAIL

  [test_console_entry_sync_callstack[debug-False\]]
    expected: FAIL

  [test_console_entry_sync_callstack[error-True\]]
    expected: FAIL

  [test_console_entry_sync_callstack[info-False\]]
    expected: FAIL

  [test_console_entry_sync_callstack[log-False\]]
    expected: FAIL

  [test_console_entry_sync_callstack[table-False\]]
    expected: FAIL

  [test_console_entry_sync_callstack[trace-True\]]
    expected: FAIL

  [test_console_entry_sync_callstack[warn-True\]]
    expected: FAIL

  [test_javascript_entry_sync_callstack]
    expected: FAIL
