[invalid.py]
  [test_params_context_invalid_type[value2\]]
    expected: FAIL
