[sandbox.py]
  [test_sandbox_returns_same_node]
    expected: FAIL
