[shared_id_node.py]
  [test_shadow_root_reference_created_in_classic[closed\]]
    expected: FAIL
